#!/usr/bin/env bash
#configure web-02 to be identical to web-01
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02
#the name of the custom HTTP header must be X-Served-By

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Holberton School" | sudo tee /var/www/html/index.ngix-debian.html
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
