#!/usr/bin/env bash
#  custom header (on web-01 and web-02) header must be X-Served-By
apt-get -y update
apt-get -y install nginx

# configure redirection page
sudo sed -i "42i location /redirect_me {\\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n}\\n" /etc/nginx/sites-available/default

# insert default page text 
echo "Hello World!" > /var/www/html/index.html

# make 404 error page and configure it
sudo sed -i "/server_name _;/a error_page 404 /notfound.html;\nlocation = /notfound.html {\nroot /var/www/html;\ninternal;\n}" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/notfound.html

#custom header hostname
sudo sed -i "40i \t #custom header hostename\n\tadd_header X-Served-By $(cat /etc/hostname);" /etc/nginx/sites-available/default
service nginx start
